services:
  - type: web
    name: course-registration-backend
    env: java
    rootDir: CourseRegistrationSystem
    buildCommand: mvn clean package
    startCommand: java -jar target/CourseRegistrationSystem-0.0.1-SNAPSHOT.jar
    plan: free
